# Generated by Django 2.2.3 on 2019-07-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True)),
                ('isPremiumOnly', models.BooleanField()),
                ('searchHitCount', models.BigIntegerField()),
            ],
        ),
    ]
